name: graphviz
version: 0.0.4
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Emscripten module for Graphviz
homepage: https://github.com/rwl/graphviz.dart
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  dispatched_worker: '>=0.0.2 <0.2.0'
dev_dependencies:
  browser: '>=0.10.0+2 <0.11.0'
transformers:
- $dart2js:
    commandLineOptions:
    - --enable-enum
